http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: "/ip"
  user:
    host: localhost
    paths: ["/users", "/users/*"]
  product:
    host: localhost
    paths: ["/products", "/products/*"]
serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
  userService:
    url: "http://users:3001"
  productService:
    url: "http://podutos:3002"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: false
  userPipeline:
    apiEndpoints:
      - user
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
  productPipeline:
    apiEndpoints:
      - product
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: productService
              changeOrigin: true
 